# How to Use Pandas with Large Data
**Note:** Not `Big Data`

- real-world data is messy.
- `pandas` is a game changer when it comes to cleaning, transforming, manipulating and analyzing data. 
- i.e. `pandas` helps to clean the mess.

**Some reflections**
-`NumPy`
    - is he fundamental library for scientific computing with Python that provides features for operations on n-arrays and matrices in Python.
    - provides `vectorization` of mathematical operations on the NumPy array type, which significantly optimizes computation with high performance and enhanced speed of execution.
    
 **What about higher level data analysis needs?**
 - `pandas` comes in handy here.
- the functionality of `pandas` is built on top of `NumPy`
- both libraries belong to the `SciPy` stack. 
- `pandas` relies heavily on NumPy array to implement its objects for manipulation and computation

The high level features and its convenient usage of pandas are what makes it the suited to data analysis.

**Large and Big Data**

- these are relative expressions
    - typically, large data is data sets that are less than 100GB.

- Pandas is very efficient with small data (usually from 100MB up to 1GB) and performance is rarely a concern.

- when dealing with `large data sets`, you will encounter low performance and long runtime resulting in insufficient memory.

**Pandas limitations when dealing with big data**

-  big data ought to be typically stored in computing clusters for higher scalability and fault tolerance. 
- can often be accessed through big data ecosystem (AWS EC2, Hadoop etc.) using e.g., PySpark.

**However:**

-  one of the way to use Pandas with large data on local machines (with certain memory constraints) is to reduce memory usage of the data.

### Example use if pandas with Large Data

- Suppose we have large data set (15 –50 GB). 
- We want to reduce the memory usage to fit into local memory for analysis (even before reading the data set to a dataframe).


**1. Read CSV file data in chunk size**

- you might be baffled at the error you encounter - that you cannot read the data from CSV file
    - issue is your local machine  memory (e.g., with 16GB of RAM) is too small for the data.


The `pandas.read_csv` function has a parameter called `chunksize` 

- `chunksize` relates to the number of rows to be read into a dataframe at any single time in order to fit into the local memory. 

**Question**
- How can you find out the number of rows and columns in your dataset?

- suppose that your data consists of more than 6 million of rows
    - you can specify a  `chunksize`  of 500,000 rows each time to divide the large data set into many smaller pieces.

In [1]:
import pandas as pd

In [19]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 10000)

### Try the straightforward loading

In [6]:
df_crime = pd.read_csv('Crimes2018.csv') # will take time

In [21]:
df_iterator = pd.read_csv('Crimes2018.csv', chunksize=5000) 
print(type(df_iterator))

<class 'pandas.io.parsers.readers.TextFileReader'>

In [22]:
a = next(df_iterator)
a

            ID Case Number                    Date  \
0     10000092    HY189866  03/18/2015 07:44:00 PM
1     10000094    HY190059  03/18/2015 11:00:00 PM
2     10000095    HY190052  03/18/2015 10:45:00 PM
3     10000096    HY190054  03/18/2015 10:30:00 PM
4     10000097    HY189976  03/18/2015 09:00:00 PM
5     10000098    HY190032  03/18/2015 10:00:00 PM
6     10000099    HY190047  03/18/2015 11:00:00 PM
7     10000100    HY189988  03/18/2015 09:35:00 PM
8     10000101    HY190020  03/18/2015 10:09:00 PM
9     10000104    HY189964  03/18/2015 09:25:00 PM
10    10000105    HY189984  03/18/2015 09:30:00 PM
11    10000108    HY189719  03/15/2015 04:10:00 PM
12    10000109    HY189966  03/18/2015 09:14:00 PM
13    10000110    HY190056  03/18/2015 10:50:00 PM
14    10000111    HY190019  03/18/2015 10:31:00 PM
15    10000112    HY189725  03/18/2015 12:55:00 PM
16    10000114    HY190071  03/18/2015 08:00:00 PM
17    10000115    HY190036  03/18/2015 09:00:00 PM
18    10000116    HY190063  03/18/2015 10:56:00 PM
19    10000117    HY190068  03/18/2015 10:45:00 PM
20    10000118    HY190031  03/18/2015 10:00:00 PM
21    10581023    HZ329792  09/01/2014 08:00:00 AM
22    10000119    HY190072  03/18/2015 11:55:00 PM
23    10000120    HY190073  03/18/2015 11:40:00 PM
24    10000123    HY189969  03/18/2015 09:44:00 PM
25    10000124    HY190060  03/18/2015 11:30:00 PM
26    10000126    HY190035  03/18/2015 10:45:00 PM
27    10000127    HY190027  03/18/2015 10:33:00 PM
28    10000129    HY190096  03/19/2015 01:20:00 AM
29    10000130    HY190003  03/18/2015 09:59:00 PM
30    10000131    HY190101  03/19/2015 01:28:00 AM
31    10000133    HY190085  03/19/2015 12:05:00 AM
32    10000134    HY190091  03/19/2015 12:35:00 AM
33    10000135    HY190087  03/19/2015 12:30:00 AM
34    10000137    HY190051  03/18/2015 10:45:00 PM
35    10000138    HY190094  03/19/2015 12:50:00 AM
36    10000139    HY190098  03/19/2015 01:15:00 AM
37    10000142    HY190058  03/18/2015 11:35:00 PM
38    10000143    HY190100  03/19/2015 02:00:00 AM
39    10000145    HY190099  03/19/2015 01:19:00 AM
40    10000146    HY190103  03/19/2015 01:50:00 AM
41    10000147    HY190102  03/19/2015 01:00:00 AM
42    10000148    HY190122  03/19/2015 02:45:00 AM
43    10000149    HY190082  03/19/2015 12:15:00 AM
44    10000151    HY190115  03/19/2015 02:26:00 AM
45    10000153    HY189345  03/18/2015 12:20:00 PM
46    10000155    HY190125  03/19/2015 02:30:00 AM
47    10000158    HY190061  03/18/2015 11:20:00 PM
48    10000159    HY190043  03/18/2015 11:00:00 PM
49    10000160    HY190116  03/18/2015 03:00:00 PM
50    10000161    HY190135  03/18/2015 04:00:00 AM
51    10000163    HY190083  03/18/2015 11:46:00 PM
52    10000164    HY190123  03/19/2015 02:55:00 AM
53    10000166    HY190133  03/19/2015 03:00:00 AM
54    10000169    HY190064  03/12/2015 10:00:00 AM
55    10000170    HY190136  03/19/2015 03:51:00 AM
56    10000171    HY190088  03/18/2015 02:30:00 PM
57    10000172    HY190131  03/19/2015 01:30:00 AM
58    10000173    HY190120  03/19/2015 02:35:00 AM
59    10000176    HY190142  03/19/2015 04:00:00 AM
60    10000178    HY190144  03/19/2015 03:34:00 AM
61    10000179    HY190111  03/19/2015 02:05:00 AM
62    10000180    HY190143  03/19/2015 04:29:00 AM
63    10000182    HY190084  03/18/2015 11:35:00 PM
64    10000184    HY190139  03/19/2015 03:11:00 AM
65    10000185    HY190119  03/19/2015 02:31:00 AM
66    10000186    HY190093  03/19/2015 12:09:00 AM
67    10000188    HY190076  03/19/2015 12:01:00 AM
68    10000190    HY190026  03/18/2015 10:30:00 PM
69    10000191    HY190013  03/18/2015 10:15:00 PM
70    10000194    HY190147  03/19/2015 04:38:00 AM
71    10000196    HY190106  03/19/2015 12:30:00 AM
72    10000197    HY190067  03/18/2015 11:20:00 PM
73    10000199    HY190149  03/19/2015 02:00:00 AM
74    10000200    HY189240  03/10/2015 08:00:00 AM
75    10000201    HY190159  03/18/2015 08:00:00 PM
76    10000202    HY190090  03/19/2015 12:35:00 AM
77    10000203    HY190151  03/19/2015 01:00:00 AM
78    10000204    HY190086  03/18/2015 05:00:00 PM
79    10000205    HY190141  03/18/2015 05:30:00 PM
80    10000207    HY189272  03/18/2015 12:20:00 PM
81    10000208    HY190156  03/19/2015 05:30:00 AM
82    10000209    HY189415  03/17/2015 12:00:00 PM
83    10000211    HY189397  03/18/2015 01:45:00 PM
84    10000212    HY189315  03/18/2015 12:50:00 PM
85    10000216    HY189182  03/17/2015 07:30:00 PM
86    10000219    HY190166  03/18/2015 07:00:00 PM
87    10000220    HY190152  03/19/2015 05:00:00 AM
88    10000227    HY190155  03/19/2015 04:52:00 AM
89    10000233    HY189165  03/18/2015 10:45:00 AM
90    10000234    HY190158  03/19/2015 05:50:00 AM
91    10000239    HY189270  03/11/2015 12:01:00 AM
92    10000241    HY188049  03/15/2015 08:45:00 PM
93    10000257    HY190157  03/19/2015 05:20:00 AM
94    10000258    HY189245  03/13/2015 03:00:00 PM
95    10000267    HY190175  03/19/2015 07:05:00 AM
96    10000268    HY189169  03/18/2015 09:00:00 AM
97    10000275    HY190183  03/18/2015 12:00:00 PM
98    10000280    HY190195  03/19/2015 07:55:00 AM
99    10000284    HY190189  03/18/2015 05:00:00 PM
100   10000290    HY190191  03/18/2015 04:00:00 PM
101   10000299    HY189997  03/18/2015 09:15:00 PM
102   10000305    HY190171  03/19/2015 07:00:00 AM
103   10000307    HY190210  03/19/2015 07:45:00 AM
104   10000312    HY190164  03/19/2015 06:07:00 AM
105   10000324    HY190190  03/19/2015 07:20:00 AM
106   10000329    HY190202  03/13/2015 07:30:00 AM
107   10000337    HY189094  03/14/2015 03:30:00 AM
108   10000345    HY190216  03/17/2015 02:00:00 PM
109   10000346    HY190229  03/18/2015 04:00:00 PM
110   10000348    HY190226  12/15/2014 04:00:00 PM
111   10000354    HY190222  03/18/2015 07:00:00 PM
112   10000361    HY190207  03/19/2015 07:15:00 AM
113   10000362    HY190214  03/18/2015 03:15:00 PM
114   10000364    HY190177  03/18/2015 06:30:00 PM
115   10000366    HY190228  03/18/2015 09:00:00 PM
116   10000372    HY190010  03/18/2015 05:01:00 PM
117   10000373    HY190186  03/19/2015 07:25:00 AM
118   10000374    HY190167  03/18/2015 07:51:00 AM
119   10000392    HY190209  03/18/2015 10:00:00 PM
120   10000395    HY190178  03/19/2015 06:50:00 AM
121   10000399    HY190193  03/19/2015 07:30:00 AM
122   10000404    HY190170  03/19/2015 07:00:00 AM
123   10000420    HY190232  03/14/2015 03:00:00 AM
124   10000423    HY190203  03/19/2015 07:10:00 AM
125    4755307    HM367521  01/23/2002 12:00:00 AM
126   10000424    HY190160  03/19/2015 05:09:00 AM
127   10000433    HY190233  03/19/2015 06:27:00 AM
128   10000440    HY190236  03/19/2015 08:30:00 AM
129   10000441    HY190200  03/19/2015 07:30:00 AM
130   10000447    HY190213  03/18/2015 11:30:00 PM
131   10000448    HY190184  03/19/2015 06:57:00 AM
132   10000451    HY190258  03/18/2015 10:00:00 AM
133   10000453    HY189295  03/18/2015 09:30:00 AM
134   10000456    HY190278  03/16/2015 09:00:00 PM
135   10000458    HY190255  03/19/2015 07:30:00 AM
136   10000459    HY190256  03/16/2015 08:00:00 PM
137   10000461    HY190271  03/01/2015 05:00:00 PM
138   10000464    HY190254  03/18/2015 09:00:00 AM
139   10000465    HY190234  12/15/2014 04:30:00 PM
140   10000466    HY190168  03/19/2015 05:10:00 AM
141   10000468    HY190163  03/14/2015 08:00:00 AM
142   10000471    HY190223  03/18/2015 01:30:00 PM
143   10000472    HY190217  02/12/2015 09:00:00 AM
144   10000473    HY190204  03/19/2015 07:59:00 AM
145   10000474    HY190206  03/19/2015 08:00:00 AM
146   10000475    HY190301  03/19/2015 12:01:00 AM
147   10000477    HY190294  03/10/2015 03:30:00 PM
148   10000489    HY189958  03/18/2015 09:35:00 PM
149   10000513    HY190279  03/18/2015 09:30:00 PM
150   10000517    HY190259  11/15/2014 12:00:00 PM
151   10000524    HY190240  02/04/2015 01:07:00 PM
152   10000536    HY190281  02/11/2015 08:00:00 AM
153   10000543    HY190305  03/19/2015 09:54:00 AM
154   10000548    HY190165  03/18/2015 09:00:00 PM
155   10000554    HY190310  03/18/2015 09:00:00 AM
156   10000556    HY190295  03/19/2015 09:30:00 AM
157   10000557    HY190270  03/19/2015 01:00:00 AM
158   10000560    HY190306  03/18/2015 03:05:00 PM
159   10000561    HY190308  03/19/2015 09:10:00 AM
160   10000566    HY190239  03/19/2015 07:55:00 AM
161   10000572    HY190319  03/19/2015 09:50:00 AM
162   10000573    HY190292  03/17/2015 11:00:00 AM
163   10000586    HY190318  03/19/2015 07:30:00 AM
164   10000588    HY190297  03/15/2015 07:30:00 AM
165   10000591    HY190339  03/17/2015 09:45:00 AM
166   10000594    HY190287  03/19/2015 01:10:00 AM
167   10000613    HY190303  03/18/2015 12:20:00 PM
168   10000617    HY134412  01/30/2015 04:57:39 PM
169   10000618    HY190345  03/13/2015 08:15:00 PM
170   10000620    HY190274  03/18/2015 01:00:00 PM
171   10000624    HY190252  03/19/2015 08:00:00 AM
172   10000628    HY172353  03/05/2015 06:35:00 AM
173   10000629    HY190218  03/19/2015 07:56:00 AM
174   10000633    HY189098  03/18/2015 10:15:00 AM
175   10000636    HY190199  03/18/2015 04:00:00 PM
176   10000646    HY190262  03/19/2015 08:45:00 AM
177   10000647    HY190340  03/19/2015 08:00:00 AM
178   10000648    HY190360  03/19/2015 10:30:00 AM
179   10000654    HY190370  01/28/2015 08:00:00 AM
180   10000662    HY190342  03/14/2015 02:00:00 PM
181   10000664    HY190391  02/01/2015 01:00:00 PM
182   10000666    HY190375  03/19/2015 10:40:00 AM
183   10000668    HY190347  02/28/2015 08:00:00 PM
184   10000678    HY190235  03/19/2015 08:40:00 AM
185   10000681    HY190286  03/19/2015 07:00:00 AM
186   10000682    HY190416  03/09/2015 08:00:00 AM
187   10000692    HY190392  03/19/2015 09:30:00 AM
188   10000693    HY189097  03/18/2015 10:20:00 AM
189   10000697    HY190407  03/19/2015 11:00:00 AM
190   10000698    HY190323  03/11/2015 12:00:00 PM
191   10000699    HY190422  03/19/2015 10:55:00 AM
192   10000700    HY190395  03/12/2015 12:00:00 PM
193   10000701    HY190349  06/20/2014 09:00:00 AM
194   10000702    HY190398  03/19/2015 11:04:00 AM
195   10000704    HY190413  03/18/2015 03:23:00 PM
196   10000705    HY190388  03/18/2015 02:30:00 PM
197   10000707    HY190335  03/19/2015 10:00:00 AM
198   10000709    HY190430  03/15/2015 03:00:00 PM
199   10000719    HY190425  03/19/2015 11:20:00 AM
200   10000732    HY190449  03/18/2015 11:50:00 PM
201   10000733    HY190446  03/18/2015 06:30:00 AM
202   10000736    HY190359  03/19/2015 09:45:00 AM
203   10000739    HY186570  03/16/2015 11:00:00 AM
204   10000746    HY190380  03/18/2015 04:40:00 PM
205   10000748    HY190353  03/19/2015 09:50:00 AM
206   10000755    HY189271  03/17/2015 09:00:00 PM
207   10000756    HY189255  03/13/2015 05:50:00 PM
208   10000760    HY190285  03/17/2015 09:00:00 AM
209   10000762    HY190376  03/19/2015 08:00:00 AM
210   10000763    HY190336  03/19/2015 03:30:00 AM
211   10000764    HY190418  03/18/2015 02:00:00 PM
212   10000765    HY190368  03/14/2015 03:00:00 PM
213   10000767    HY190181  03/18/2015 02:30:00 PM
214   10000768    HY190357  03/19/2015 10:15:00 AM
215   10000769    HY190432  03/19/2015 11:15:00 AM
216   10000770    HY190243  03/18/2015 04:30:00 PM
217   10000771    HY190424  03/14/2015 01:00:00 AM
218   10000773    HY190238  03/19/2015 08:30:00 AM
219   10000775    HY190341  03/19/2015 09:51:00 AM
220   10000776    HY190384  03/17/2015 11:00:00 AM
221   10000777    HY190417  03/18/2015 08:38:00 AM
222   10000778    HY190471  03/19/2015 11:50:00 AM
223   10000779    HY190441  03/19/2015 02:30:00 AM
224   10000780    HY190385  03/19/2015 10:08:00 AM
225   10000782    HY190406  03/19/2015 10:15:00 AM
226   10000785    HY193337  03/11/2015 05:00:00 PM
227   10000787    HY186758  03/16/2015 01:25:00 PM
228   10000791    HY190350  03/19/2015 10:20:00 AM
229   10000792    HY190477  03/18/2015 03:05:00 PM
230   10000795    HY190431  03/19/2015 11:25:00 AM
231   10000796    HY190447  03/19/2015 02:30:00 AM
232   10000797    HY190390  03/19/2015 11:00:00 AM
233   10000802    HY190488  03/19/2015 03:00:00 AM
234   10000803    HY190483  03/19/2015 09:00:00 AM
235   10000804    HY190472  03/18/2015 11:00:00 PM
236   10000806    HY190326  03/19/2015 09:45:00 AM
237   10000807    HY190386  03/18/2015 10:45:00 AM
238   10000811    HY190489  03/18/2015 09:00:00 PM
239   10000814    HY133401  01/29/2015 06:16:44 PM
240   10000819    HY190460  03/19/2015 11:27:00 AM
241   10000823    HY190506  03/19/2015 12:20:00 PM
242   10000824    HY190491  03/19/2015 11:05:00 AM
243   10000828    HY190427  03/18/2015 07:00:00 PM
244   10000829    HY190478  03/19/2015 11:27:00 AM
245   10000836    HY190419  03/19/2015 11:00:00 AM
246   10000841    HY190445  03/19/2015 11:40:00 AM
247   10000842    HY190315  03/19/2015 09:15:00 AM
248   10000845    HY190514  03/15/2014 09:00:00 AM
249   10000846    HY190366  03/19/2015 10:20:00 AM
250   10000849    HY190443  03/12/2015 01:00:00 PM
251   10000854    HY190402  03/18/2015 10:15:00 AM
252   10000856    HY190461  03/16/2015 09:00:00 AM
253   10000857    HY190486  03/19/2015 06:00:00 AM
254   10000859    HY190444  03/19/2015 11:10:00 AM
255   10000861    HY123079  01/20/2015 06:10:00 PM
256   10000867    HY190338  03/19/2015 09:20:00 AM
257   10000869    HY190408  03/19/2015 10:30:00 AM
258   10000870    HY190363  03/19/2015 10:38:00 AM
259   10000872    HY190496  03/19/2015 12:15:00 PM
260   10000874    HY190518  03/19/2015 12:22:00 PM
261   10000875    HY190539  03/19/2015 12:20:00 PM
262   10000879    HY133975  01/30/2015 11:50:18 AM
263   10000883    HY190211  03/16/2015 07:00:00 AM
264   10000884    HY190541  03/12/2015 06:30:00 PM
265   10000889    HY190490  03/18/2015 10:00:00 AM
266   10000893    HY190463  03/19/2015 11:40:00 AM
267   10000895    HY190538  03/19/2015 12:42:00 PM
268   10000896    HY190379  03/18/2015 01:00:00 AM
269   10000901    HY190314  03/19/2015 05:00:00 AM
270   10000902    HY190435  03/17/2015 10:00:00 AM
271   10000903    HY138419  02/03/2015 03:38:00 PM
272   10000905    HY190469  02/27/2015 09:00:00 AM
273   10000906    HY190513  03/19/2015 12:20:00 PM
274   10000911    HY190563  01/11/2015 10:00:00 AM
275   10000912    HY190521  03/18/2015 06:20:00 PM
276   10000913    HY190516  03/19/2015 12:30:00 PM
277   10000914    HY190304  03/19/2015 09:30:00 AM
278   10000922    HY190519  03/19/2015 07:00:00 AM
279   10000923    HY190548  03/19/2015 01:00:00 AM
280   10000926    HY190527  03/19/2015 12:00:00 PM
281   10000928    HY190502  03/19/2015 12:27:00 PM
282   10000929    HY190572  03/19/2015 09:30:00 AM
283   10000931    HY190529  02/16/2015 06:45:00 AM
284   10000933    HY190485  03/18/2015 07:00:00 AM
285   10000934    HY190525  03/19/2015 11:35:00 AM
286   10000935    HY190448  03/19/2015 11:45:00 AM
287   10000936    HY190437  03/15/2015 05:30:00 PM
288   10000940    HY190356  03/19/2015 10:16:00 AM
289   10000942    HY190480  02/19/2015 01:30:00 PM
290   10000943    HY190588  03/19/2015 01:35:00 PM
291   10000946    HY190173  03/19/2015 03:00:00 AM
292   10000947    HY190565  03/19/2015 12:53:00 PM
293   10000951    HY190535  03/19/2015 12:05:00 PM
294   10000954    HY190498  01/01/2015 08:00:00 AM
295   10000964    HY190593  03/09/2015 01:00:00 PM
296   10000969    HY190597  03/19/2015 01:00:00 PM
297   10000972    HY190343  03/19/2015 10:00:00 AM
298   10000973    HY190554  01/26/2015 04:01:00 PM
299   10000974    HY190405  01/23/2015 09:00:00 AM
300   10000975    HY190495  03/19/2015 11:45:00 AM
301   10000976    HY190526  03/19/2015 12:25:00 PM
302   10000989    HY190545  03/19/2015 12:30:00 PM
303   10000991    HY190481  03/19/2015 12:05:00 PM
304   10000993    HY174332  03/06/2015 05:38:00 PM
305   10000994    HY190455  03/19/2015 10:20:00 AM
306   10000996    HY190454  03/19/2015 12:10:00 PM
307   10000997    HY190450  03/19/2015 10:40:00 AM
308   10000998    HY190555  03/19/2015 12:04:00 PM
309   10001000    HY190559  03/19/2015 10:00:00 AM
310   10001003    HY190542  10/20/2014 08:00:00 AM
311   10001004    HY190289  03/13/2015 11:35:00 AM
312   10001005    HY190567  03/12/2015 08:00:00 AM
313   10001006    HY190522  03/19/2015 12:00:00 PM
314   10001010    HY174329  03/06/2015 12:38:00 PM
315   10001011    HY190550  03/18/2015 09:00:00 PM
316   10001012    HY190602  03/16/2015 12:00:00 PM
317   10001013    HY190606  03/16/2015 08:30:00 AM
318   10001017    HY190547  03/19/2015 12:00:00 PM
319   10001020    HY190267  03/19/2015 08:45:00 AM
320   10001023    HY190556  03/19/2015 01:10:00 PM
321   10001026    HY174264  03/06/2015 01:40:00 PM
322   10001031    HY190394  03/19/2015 11:05:00 AM
323   10001033    HY190599  03/18/2015 03:00:00 PM
324   10001035    HY190631  03/15/2015 04:30:00 PM
325   10001036    HY190637  03/19/2015 01:30:00 PM
326   10001037    HY190573  03/19/2015 12:15:00 PM
327   10001040    HY190566  03/19/2015 09:36:00 AM
328   10001042    HY190617  03/19/2015 01:45:00 PM
329   10001050    HY172795  03/05/2015 01:41:00 PM
330   10001062    HY172764  03/05/2015 01:40:00 PM
331   10001063    HY190374  03/19/2015 07:30:00 AM
332   10001064    HY190601  03/19/2015 01:01:00 PM
333   10001065    HY190626  03/19/2015 12:30:00 PM
334   10001068    HY190311  03/19/2015 09:30:00 AM
335   10001070    HY190645  03/09/2015 09:00:00 AM
336   10001075    HY173967  03/06/2015 01:50:00 PM
337   10001085    HY190618  03/19/2015 01:31:00 PM
338   10001098    HY190510  02/28/2015 11:09:00 PM
339   10001101    HY190581  03/19/2015 12:00:00 PM
340   10001105    HY190586  03/19/2015 01:10:00 PM
341   10001106    HY190536  03/19/2015 12:25:00 PM
342   10001110    HY190528  03/19/2015 11:54:00 AM
343   10001112    HY190612  03/19/2015 12:30:00 PM
344   10001116    HY190568  03/19/2015 12:52:00 PM
345   10001118    HY190635  03/19/2015 01:30:00 PM
346   10001119    HY190512  03/19/2015 11:25:00 AM
347   10001120    HY190674  03/13/2015 02:00:00 PM
348   10001121    HY190659  03/19/2015 02:17:00 PM
349   10001122    HY189858  03/18/2015 05:13:00 PM
350   10001124    HY190053  03/18/2015 11:20:00 PM
351   10001125    HY190018  03/18/2015 09:30:00 PM
352   10001127    HY190007  03/18/2015 10:20:00 AM
353   10001128    HY189817  03/18/2015 06:39:00 PM
354   10001129    HY190649  03/19/2015 02:00:00 PM
355   10001130    HY190614  03/19/2015 01:50:00 PM
356   10001132    HY190452  03/18/2015 09:00:00 AM
357   10001133    HY189975  03/18/2015 09:50:00 PM
358   10001134    HY190577  03/19/2015 12:45:00 PM
359   10001135    HY189558  03/18/2015 04:00:00 PM
360   10001136    HY189589  03/18/2015 04:30:00 PM
361   10001138    HY189841  03/18/2015 07:20:00 PM
362   10001139    HY190656  03/19/2015 08:00:00 AM
363   10001141    HY190686  10/07/2014 02:00:00 PM
364   10001142    HY179885  03/11/2015 09:15:00 AM
365   10001143    HY187772  03/17/2015 09:30:00 AM
366   10001145    HY190695  03/19/2015 02:30:00 PM
367   10001146    HY190688  03/19/2015 02:00:00 PM
368   10001147    HY190698  03/19/2015 03:10:00 PM
369   10001148    HY190691  03/19/2015 01:00:00 PM
370   10001149    HY190721  03/18/2015 06:00:00 PM
371   10001152    HY190692  03/19/2015 02:50:00 PM
372   10001154    HY190580  03/15/2015 05:00:00 PM
373   10001157    HY190652  03/19/2015 02:15:00 PM
374   10001158    HY190697  03/19/2015 02:30:00 PM
375   10001159    HY190653  03/05/2015 04:30:00 PM
376   10001160    HY190587  03/19/2015 08:11:00 AM
377   10001161    HY190671  03/19/2015 02:00:00 PM
378   10001163    HY190718  03/18/2015 09:00:00 PM
379   10001170    HY190664  10/01/2014 07:00:00 AM
380   10001171    HY190726  03/19/2015 11:30:00 AM
381   10001172    HY190668  03/12/2015 04:00:00 PM
382   10001173    HY190738  03/19/2015 03:10:00 PM
383   10001174    HY190643  03/16/2015 04:30:00 PM
384   10001175    HY190657  03/19/2015 08:30:00 AM
385   10001179    HY190639  03/19/2015 01:45:00 PM
386   10001180    HY190642  03/19/2015 07:51:00 AM
387   10001181    HY190605  03/19/2015 11:25:00 AM
388   10001182    HY190708  03/18/2015 09:00:00 AM
389   10001183    HY190655  03/19/2015 12:40:00 PM
390   10001184    HY190672  03/11/2015 09:00:00 AM

In [17]:
res = None
for chunk in pd.read_csv("Crimes2018.csv", chunksize=10000):
    location = chunk["Location Description"]
    chunk_result = location.value_counts()
    if res is None:
        res = chunk_result
    else:
        res = res.add(chunk_result, fill_value=0)

res.sort_values(ascending=False, inplace=True)
print(res[:10])

Location Description
STREET                            1770601.0
RESIDENCE                         1142451.0
APARTMENT                          697292.0
SIDEWALK                           665415.0
OTHER                              256428.0
PARKING LOT/GARAGE(NON.RESID.)     193801.0
ALLEY                              150881.0
SCHOOL, PUBLIC, BUILDING           142257.0
RESIDENCE-GARAGE                   131632.0
SMALL RETAIL STORE                 119254.0
Name: count, dtype: float64

**Memory usage**

In [15]:
df_crime.memory_usage().sum()/(1024**3) #GB

1.0179547667503357

In [19]:
df_crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6747040 entries, 0 to 6747039
Data columns (total 22 columns):
 #   Column                Dtype
---  ------                -----
 0   ID                    int64
 1   Case Number           object
 2   Date                  object
 3   Block                 object
 4   IUCR                  object
 5   Primary Type          object
 6   Description           object
 7   Location Description  object
 8   Arrest                bool
 9   Domestic              bool
 10  Beat                  int64
 11  District              float64
 12  Ward                  float64
 13  Community Area        float64
 14  FBI Code              object
 15  X Coordinate          float64
 16  Y Coordinate          float64
 17  Year                  int64
 18  Updated On            object
 19  Latitude              float64
 20  Longitude             float64
 21  Location              object
dtypes: bool(2), float64(7), int64(3), object(10)
memory usage: 1.0+ GB

**Now read with chunksize**

In [25]:
df_chunk = pd.read_csv('Crimes2018.csv', chunksize=500000)

In [21]:
# what does this do
reader = pd.read_csv('Crimes2018.csv', iterator=True)
reader.get_chunk(10)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10000092,HY189866,03/18/2015 07:44:00 PM,047XX W OHIO ST,041A,BATTERY,AGGRAVATED: HANDGUN,STREET,False,False,1111,11,28,25,04B,1144606,1903566,2015,02/10/2018 03:50:01 PM,41.891399,-87.744385,"(41.891398861, -87.744384567)"
1,10000094,HY190059,03/18/2015 11:00:00 PM,066XX S MARSHFIELD AVE,4625,OTHER OFFENSE,PAROLE VIOLATION,STREET,True,False,725,7,15,67,26,1166468,1860715,2015,02/10/2018 03:50:01 PM,41.773372,-87.665319,"(41.773371528, -87.665319468)"
2,10000095,HY190052,03/18/2015 10:45:00 PM,044XX S LAKE PARK AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,222,2,4,39,08B,1185075,1875622,2015,02/10/2018 03:50:01 PM,41.813861,-87.596643,"(41.81386068, -87.596642837)"
3,10000096,HY190054,03/18/2015 10:30:00 PM,051XX S MICHIGAN AVE,0460,BATTERY,SIMPLE,APARTMENT,False,False,225,2,3,40,08B,1178033,1870804,2015,02/10/2018 03:50:01 PM,41.800802,-87.622619,"(41.800802415, -87.622619343)"
4,10000097,HY189976,03/18/2015 09:00:00 PM,047XX W ADAMS ST,031A,ROBBERY,ARMED: HANDGUN,SIDEWALK,False,False,1113,11,28,25,03,1144920,1898709,2015,02/10/2018 03:50:01 PM,41.878065,-87.743354,"(41.878064761, -87.743354013)"
5,10000098,HY190032,03/18/2015 10:00:00 PM,049XX S DREXEL BLVD,0460,BATTERY,SIMPLE,APARTMENT,False,False,223,2,4,39,08B,1183018,1872537,2015,02/10/2018 03:50:01 PM,41.805443,-87.604284,"(41.805443345, -87.604283976)"
6,10000099,HY190047,03/18/2015 11:00:00 PM,070XX S MORGAN ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,733,7,17,68,08B,1170859,1858210,2015,02/10/2018 03:50:01 PM,41.766403,-87.649296,"(41.766402779, -87.649296123)"
7,10000100,HY189988,03/18/2015 09:35:00 PM,042XX S PRAIRIE AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,213,2,3,38,08B,1178746,1876914,2015,02/10/2018 03:50:01 PM,41.817553,-87.619819,"(41.817552577, -87.619818523)"
8,10000101,HY190020,03/18/2015 10:09:00 PM,036XX S WOLCOTT AVE,1811,NARCOTICS,POSS: CANNABIS 30GMS OR LESS,STREET,True,False,912,9,11,59,18,1164279,1880656,2015,02/10/2018 03:50:01 PM,41.828138,-87.672782,"(41.828138428, -87.672782106)"
9,10000104,HY189964,03/18/2015 09:25:00 PM,097XX S PRAIRIE AVE,0460,BATTERY,SIMPLE,RESIDENCE PORCH/HALLWAY,False,False,511,5,6,49,08B,1179637,1840444,2015,02/10/2018 03:50:01 PM,41.717455,-87.617663,"(41.71745472, -87.617663257)"

In [11]:
reader.get_chunk(10)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
10,10000105,HY189984,03/18/2015 09:30:00 PM,130XX S DR MARTIN LUTHER KING JR DR,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT/GARAGE(NON.RESID.),False,False,...,9,54,14,1180907,1818839,2015,02/10/2018 03:50:01 PM,41.658138,-87.613673,"(41.658138493, -87.613672862)"
11,10000108,HY189719,03/15/2015 04:10:00 PM,078XX S VINCENNES AVE,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,CTA GARAGE / OTHER PROPERTY,False,True,...,17,69,26,1175130,1853144,2015,02/10/2018 03:50:01 PM,41.752407,-87.633792,"(41.752406801, -87.633792381)"
12,10000109,HY189966,03/18/2015 09:14:00 PM,086XX S EXCHANGE AVE,143A,WEAPONS VIOLATION,UNLAWFUL POSS OF HANDGUN,DRIVEWAY - RESIDENTIAL,True,False,...,10,46,15,1197309,1848290,2015,02/10/2018 03:50:01 PM,41.738563,-87.552679,"(41.738563465, -87.552678593)"
13,10000110,HY190056,03/18/2015 10:50:00 PM,014XX S ASHLAND AVE,0460,BATTERY,SIMPLE,SIDEWALK,False,False,...,2,28,08B,1165950,1893388,2015,02/10/2018 03:50:01 PM,41.863041,-87.666289,"(41.86304084, -87.666288555)"
14,10000111,HY190019,03/18/2015 10:31:00 PM,051XX W CHICAGO AVE,0860,THEFT,RETAIL THEFT,GAS STATION,True,False,...,37,25,06,1141741,1904839,2015,02/10/2018 03:50:01 PM,41.894946,-87.754875,"(41.894945606, -87.754874977)"
15,10000112,HY189725,03/18/2015 12:55:00 PM,077XX S KINGSTON AVE,0610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,...,7,43,05,1194535,1854110,2015,02/10/2018 03:50:01 PM,41.754603,-87.562651,"(41.754602618, -87.562650741)"
16,10000114,HY190071,03/18/2015 08:00:00 PM,024XX W NORTH AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,OTHER,False,False,...,1,24,07,1159959,1910569,2015,02/10/2018 03:50:01 PM,41.910313,-87.687806,"(41.910312648, -87.687806494)"
17,10000115,HY190036,03/18/2015 09:00:00 PM,069XX S LOOMIS BLVD,0890,THEFT,FROM BUILDING,GROCERY FOOD STORE,False,False,...,17,67,06,1168192,1858832,2015,02/10/2018 03:50:01 PM,41.768167,-87.659054,"(41.768167414, -87.659053795)"
18,10000116,HY190063,03/18/2015 10:56:00 PM,105XX S LAFAYETTE AVE,0470,PUBLIC PEACE VIOLATION,RECKLESS CONDUCT,ALLEY,True,False,...,34,49,24,1177790,1835106,2015,02/10/2018 03:50:01 PM,41.702848,-87.624589,"(41.70284845, -87.624588931)"
19,10000117,HY190068,03/18/2015 10:45:00 PM,087XX S KIMBARK AVE,0890,THEFT,FROM BUILDING,BAR OR TAVERN,False,False,...,8,48,06,1186312,1847473,2015,02/10/2018 03:50:01 PM,41.736588,-87.592994,"(41.736588206, -87.59299436)"

In [12]:
type(reader)

pandas.io.parsers.readers.TextFileReader

### What really is df_chunk?
- The operation above resulted in a `TextFileReader` object. 
- `df_chunk` is not a dataframe but an object for further operation.

**Basic workflow**

- perform operation on each chunk and concatenate each of them to form a dataframe in the end 
- you can iterate each chunk, perform data filtering/preprocessing using a function- chunk_preprocessing before appending each chunk to a list. 
- finally, concatenate the list into a final dataframe to fit into the local memory.

In [27]:
chunk_list = []  # append each chunk df here 

# Each chunk is in df format
for chunk in df_chunk:  
    chunk_list.append(chunk)
    
# concat the list into dataframe 
df_concat = pd.concat(chunk_list)

In [28]:
df_concat.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10000092,HY189866,03/18/2015 07:44:00 PM,047XX W OHIO ST,041A,BATTERY,AGGRAVATED: HANDGUN,STREET,False,False,1111,11.0,28.0,25.0,04B,1144606.0,1903566.0,2015,02/10/2018 03:50:01 PM,41.891399,-87.744385,"(41.891398861, -87.744384567)"
1,10000094,HY190059,03/18/2015 11:00:00 PM,066XX S MARSHFIELD AVE,4625,OTHER OFFENSE,PAROLE VIOLATION,STREET,True,False,725,7.0,15.0,67.0,26,1166468.0,1860715.0,2015,02/10/2018 03:50:01 PM,41.773372,-87.665319,"(41.773371528, -87.665319468)"
2,10000095,HY190052,03/18/2015 10:45:00 PM,044XX S LAKE PARK AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,222,2.0,4.0,39.0,08B,1185075.0,1875622.0,2015,02/10/2018 03:50:01 PM,41.813861,-87.596643,"(41.81386068, -87.596642837)"
3,10000096,HY190054,03/18/2015 10:30:00 PM,051XX S MICHIGAN AVE,0460,BATTERY,SIMPLE,APARTMENT,False,False,225,2.0,3.0,40.0,08B,1178033.0,1870804.0,2015,02/10/2018 03:50:01 PM,41.800802,-87.622619,"(41.800802415, -87.622619343)"
4,10000097,HY189976,03/18/2015 09:00:00 PM,047XX W ADAMS ST,031A,ROBBERY,ARMED: HANDGUN,SIDEWALK,False,False,1113,11.0,28.0,25.0,03,1144920.0,1898709.0,2015,02/10/2018 03:50:01 PM,41.878065,-87.743354,"(41.878064761, -87.743354013)"

### some other processing chunk by chunk
- our chunksize of 500,000 means that Pandas reads 500,000 rows each time and returns iterable called `reader`

- we can perform any operation on this reader object. Once the processing on this object is done, Pandas reads next 500,000 records and the process continues until all the records are processed.

In [15]:
df_concat.memory_usage() # in bytes

Index                        128
ID                      53976320
Case Number             53976320
Date                    53976320
Block                   53976320
IUCR                    53976320
Primary Type            53976320
Description             53976320
Location Description    53976320
Arrest                   6747040
Domestic                 6747040
Beat                    53976320
District                53976320
Ward                    53976320
Community Area          53976320
FBI Code                53976320
X Coordinate            53976320
Y Coordinate            53976320
Year                    53976320
Updated On              53976320
Latitude                53976320
Longitude               53976320
Location                53976320
dtype: int64

In [31]:
df_concat.dtypes

ID                        int64
Case Number              object
Date                     object
Block                    object
IUCR                     object
Primary Type             object
Description              object
Location Description     object
Arrest                     bool
Domestic                   bool
Beat                      int64
District                float64
Ward                    float64
Community Area          float64
FBI Code                 object
X Coordinate            float64
Y Coordinate            float64
Year                      int64
Updated On               object
Latitude                float64
Longitude               float64
Location                 object
dtype: object

In [37]:
df_concat.shape

(6747040, 22)

In [38]:
df_concat.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10000092,HY189866,03/18/2015 07:44:00 PM,047XX W OHIO ST,041A,BATTERY,AGGRAVATED: HANDGUN,STREET,False,False,...,28.0,25.0,04B,1144606.0,1903566.0,2015,02/10/2018 03:50:01 PM,41.891399,-87.744385,"(41.891398861, -87.744384567)"
1,10000094,HY190059,03/18/2015 11:00:00 PM,066XX S MARSHFIELD AVE,4625,OTHER OFFENSE,PAROLE VIOLATION,STREET,True,False,...,15.0,67.0,26,1166468.0,1860715.0,2015,02/10/2018 03:50:01 PM,41.773372,-87.665319,"(41.773371528, -87.665319468)"
2,10000095,HY190052,03/18/2015 10:45:00 PM,044XX S LAKE PARK AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,...,4.0,39.0,08B,1185075.0,1875622.0,2015,02/10/2018 03:50:01 PM,41.813861,-87.596643,"(41.81386068, -87.596642837)"
3,10000096,HY190054,03/18/2015 10:30:00 PM,051XX S MICHIGAN AVE,0460,BATTERY,SIMPLE,APARTMENT,False,False,...,3.0,40.0,08B,1178033.0,1870804.0,2015,02/10/2018 03:50:01 PM,41.800802,-87.622619,"(41.800802415, -87.622619343)"
4,10000097,HY189976,03/18/2015 09:00:00 PM,047XX W ADAMS ST,031A,ROBBERY,ARMED: HANDGUN,SIDEWALK,False,False,...,28.0,25.0,03,1144920.0,1898709.0,2015,02/10/2018 03:50:01 PM,41.878065,-87.743354,"(41.878064761, -87.743354013)"

## Another technique to save memory
**Filter out unimportant columns**

In [33]:
df_concat.drop(['Latitude','Longitude','Location','Y Coordinate', 'X Coordinate'], axis = 1, inplace = True)

In [35]:
df_concat.memory_usage().sum()/(1024**3) #GB

0.766607940196991

In [37]:
df_concat.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,Year,Updated On
0,10000092,HY189866,03/18/2015 07:44:00 PM,047XX W OHIO ST,041A,BATTERY,AGGRAVATED: HANDGUN,STREET,False,False,1111,11.0,28.0,25.0,04B,2015,02/10/2018 03:50:01 PM
1,10000094,HY190059,03/18/2015 11:00:00 PM,066XX S MARSHFIELD AVE,4625,OTHER OFFENSE,PAROLE VIOLATION,STREET,True,False,725,7.0,15.0,67.0,26,2015,02/10/2018 03:50:01 PM
2,10000095,HY190052,03/18/2015 10:45:00 PM,044XX S LAKE PARK AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,222,2.0,4.0,39.0,08B,2015,02/10/2018 03:50:01 PM
3,10000096,HY190054,03/18/2015 10:30:00 PM,051XX S MICHIGAN AVE,0460,BATTERY,SIMPLE,APARTMENT,False,False,225,2.0,3.0,40.0,08B,2015,02/10/2018 03:50:01 PM
4,10000097,HY189976,03/18/2015 09:00:00 PM,047XX W ADAMS ST,031A,ROBBERY,ARMED: HANDGUN,SIDEWALK,False,False,1113,11.0,28.0,25.0,03,2015,02/10/2018 03:50:01 PM

### Another technique to save memory
**Change dtypes of columns**

-  use `astype()` function to change data type of column.

- changing data types in Pandas is extremely helpful to save memory, especially if you have large data for intense analysis or computation 

- By reducing the bits required to store the data, we can reduce the overall memory usage by the data up to 50%

In [42]:
# what dtypes have you got?
df_concat.dtypes

ID                        int64
Case Number              object
Date                     object
Block                    object
IUCR                     object
Primary Type             object
Description              object
Location Description     object
Arrest                     bool
Domestic                   bool
Beat                      int64
District                float64
Ward                    float64
Community Area          float64
FBI Code                 object
Year                      int64
Updated On               object
dtype: object

In [43]:
df_concat.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,Year,Updated On
0,10000092,HY189866,03/18/2015 07:44:00 PM,047XX W OHIO ST,041A,BATTERY,AGGRAVATED: HANDGUN,STREET,False,False,1111,11.0,28.0,25.0,04B,2015,02/10/2018 03:50:01 PM
1,10000094,HY190059,03/18/2015 11:00:00 PM,066XX S MARSHFIELD AVE,4625,OTHER OFFENSE,PAROLE VIOLATION,STREET,True,False,725,7.0,15.0,67.0,26,2015,02/10/2018 03:50:01 PM
2,10000095,HY190052,03/18/2015 10:45:00 PM,044XX S LAKE PARK AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,222,2.0,4.0,39.0,08B,2015,02/10/2018 03:50:01 PM
3,10000096,HY190054,03/18/2015 10:30:00 PM,051XX S MICHIGAN AVE,0460,BATTERY,SIMPLE,APARTMENT,False,False,225,2.0,3.0,40.0,08B,2015,02/10/2018 03:50:01 PM
4,10000097,HY189976,03/18/2015 09:00:00 PM,047XX W ADAMS ST,031A,ROBBERY,ARMED: HANDGUN,SIDEWALK,False,False,1113,11.0,28.0,25.0,03,2015,02/10/2018 03:50:01 PM

In [39]:
# We experiment with Ward and Community Area - to change their types
# first fill missing values with -1 for Ward and -2 for Community Area

df_concat['Ward'].fillna(-1,  inplace = True)
df_concat['Community Area'].fillna(-2, inplace = True)

In [23]:
# change ID to int32, Ward to float32, Community Area to float32

df_concat[['Ward']] = df_concat[['Ward']].astype('int32')

In [49]:
df_concat[['Ward', 'Community Area']] = df_concat[['Ward', 'Community Area']].astype('int32')

In [51]:
df_concat.dtypes

ID                        int64
Case Number              object
Date                     object
Block                    object
IUCR                     object
Primary Type             object
Description              object
Location Description     object
Arrest                     bool
Domestic                   bool
Beat                      int64
District                float64
Ward                      int32
Community Area            int32
FBI Code                 object
Year                      int64
Updated On               object
dtype: object

In [53]:
df_concat.memory_usage().sum()/(1024**3)

0.716338574886322

In [23]:
df_concat.memory_usage()

Index                        128
ID                      53976320
Case Number             53976320
Date                    53976320
Block                   53976320
IUCR                    53976320
Primary Type            53976320
Description             53976320
Location Description    53976320
Arrest                   6747040
Domestic                 6747040
Beat                    53976320
District                53976320
Ward                    26988160
Community Area          26988160
FBI Code                53976320
Year                    53976320
Updated On              53976320
dtype: int64

In [48]:
df_concat.memory_usage().sum()/(1024**3) #GB

0.716338574886322

### More nuances on memory use management

**Improving code structure**

- Our issue again is - we have a large chunk of data - e.g., a NumPy array, or a Pandas DataFrame
- we need to do a series of operations on it. 

By default both libraries make copies of the data, which means you’re using even more RAM.


So what can you do?

Consider the function below:

In [ ]:
first = 21
int first = 21

def get_s():
    return -1


public int get_s():
    return -1

In [ ]:
self.balance = self.balance + amount
self.balance+=amount

In [ ]:
import numpy as np

def normalize(array: np.ndarray) -> np.ndarray:
    """
    Takes a floating point array.
    
    Return a normalized array with values between 0 and 1.
    """
    low = array.min()
    high = array.max()
    return (array - low) / (high - low)




def normalize_in_place(array: np.ndarray):
    low = array.min()
    high = array.max()
    array -= low
    array /= high - low

#### Reflection - what the function does
- a call to the function with an array whose values range from 30 to 60, 30 will become 0.0, 45 will become 0.5, and 60 will become 1.


**How much memory does this function use?**
- If the array uses `A bytes`, the function will use `3*A` bytes of RAM:
    - The original array, which is unmodified.
    - The array - low temporary array.
    - The result that gets returned from the function.
    
    
 **A better solution is `in-place modification (mutation))`
 
 
-  use in-place operations like `+=` to do those operations on the original array:

In [ ]:
def normalize_in_place(array: np.ndarray):
    low = array.min()
    high = array.max()
    array -= low
    array /= high - low

### On pandas again
**Measuring the memory usage of a Pandas DataFrame**

**Question** - how much memory is your series or Dataframe using?

In [ ]:
import pandas as pd
series = pd.Series(["abcdefhjiklmnopqrstuvwxyz" * 10 for i in range(1000000)])

In [ ]:
series.memory_usage()

In [ ]:
series.memory_usage(deep=True)

Which is correct, is memory usage 8MB or 300MB? Neither!

In this special case, it’s actually 67MB, at least with the default Python interpreter. This is partially because I cheated, and often 300MB will actually be closer to the truth.

What’s going on? Let’s find out!


**The easy case:** numbers and other fixed-size objects


- Most Pandas columns are stored as NumPy arrays
- for types like integers or floats the values are stored inside the array itself. 
    -  example - if you have an array with 1,000,000 64-bit integers, each integer will always use 8 bytes of memory. The array in total will therefore use 8,000,000 bytes of RAM, plus some minor bookkeeping overhead:

In [ ]:
series = pd.Series([123] * 1000000, dtype=np.int64)
series.memory_usage()

In [ ]:
series.memory_usage(deep=True)

**Thought**
- For any type that has a fixed size in memory–integers, floats, categoricals, and so on–both memory_usage() variants should give the same answer, and a pretty accurate one.

**The challenging case** - arbitrarily-sized objects

 
- Different Python strings use different amounts of memory
    - the string `abc` will use far less memory than a string containing the complete works of William Shakespeare.
    - i.e.  storing arbitrary Python objects requires arbitrary amounts of memory.

- So how do we represent these differently sized strings in NumPy, and by extension in Pandas? 

    - Instead of the storing the actual strings, NumPy stores an array of pointers to those objects
        - each pointer takes 8 bytes on modern computers. The pointers point to an address in memory where the string is actually stored. And that brings us to the deep option.

Typically, Pandas returns the memory used just by the NumPy array it’s using to store the data. For strings, this is just 8 multiplied by the number of strings in the column, since NumPy is just storing 64-bit pointers. However, that’s not all the memory being used: there’s also the memory being used by the strings themselves. 
    - With `deep=False`, the memory used by the strings is not counted; with `deep=True`, it is.

We can use `sys.sizeof()` to get the memory usage of an individual object, and we can use this to verify what `deep=True` is measuring:

In [ ]:
import pandas as pd
import sys

series = pd.Series(["abcdefhjiklmnopqrstuvwxyz" * 10 for i in range(1_000_000)])
series.memory_usage()

In [ ]:
series.memory_usage(deep=True)

In [ ]:
sum([sys.getsizeof(s) for s in series]) + series.memory_usage()

**In general, use `memory_usage(deep=True)`, since it will give you a more accurate answer**

### Reducing Pandas memory usage 
**Reading in chunks**

- Your data file might be so large you can’t load it into memory at all, even with compression. So how do you process it quickly?

- By loading and then processing the data in `chunks`, you can load only part of the file into memory at any given time. And that means you can process files that don’t fit in memory.


**Example-** Reading the full file
- we start with a program that just loads a full CSV into memory. 
- we write a program that loads a employees data, and measures how many departments employees work in:

In [ ]:
d = pd.read_csv('1976-2020-senate.csv', encoding="ISO-8859-1")
d.info()

In [ ]:
import pandas

depts = pandas.read_csv(
    "employee.csv")['Department']
print(depts.value_counts())

**Thoughts**

- the bulk of memory usage is allocated by loading the CSV into memory.


Pandas allows you to `read data in chunks`
- load only some of the lines into memory at any given time.

-  if we use the `chunksize` argument to `pandas.read_csv`, we get back an iterator over DataFrames, rather than one single DataFrame. Each DataFrame is the next 1000 lines of the CSV:

In [ ]:
import pandas

result = None
for chunk in pandas.read_csv("employee.csv", chunksize=1000):
    depts = chunk["Department"]
    chunk_result = depts.value_counts()
    if result is None:
        result = chunk_result
    else:
        result = result.add(chunk_result, fill_value=0)

result.sort_values(ascending=False, inplace=True)
print(result)

If we look at the memory usage, we’ve reduced memory usage so much that the memory usage is now dominated by importing Pandas; the actual code barely uses anything